#!/usr/bin/with-contenv bash
# shellcheck disable=SC2191
# ==============================================================================
# Community Hass.io Add-ons: InfluxDB
# Runs the Chronograf Server
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

declare -a options
declare secret

# Wait for InfluxDB to become available
s6-svwait -u -t 5000 /var/run/s6/services/influxdb

# Wait for Kapacitor to become available
s6-svwait -u -t 5000 /var/run/s6/services/kapacitor

secret=$(</data/secret)

# Wait for InfluxDB...
hass.log.info "Chronograf is waiting until InfluxDB is available..."
for i in {1800..0}; do
    if influx \
        -execute "SHOW DATABASES" \
        -username "chronograf" \
        -password "${secret}" \
        > /dev/null 2>&1; then
        break;
    fi
    sleep 5
done

if [[ "$i" = 0 ]]; then
    hass.log.warning "Chronograf is done waiting. Starting anyway..."
fi

hass.log.info 'Starting Chronograf'

options+=(--host="127.0.0.1")
options+=(--port=8889)
options+=(--bolt-path=/data/chronograf.db)
options+=(--influxdb-url="http://localhost:8086")

options+=(--influxdb-username="chronograf")
options+=(--influxdb-password="${secret}")
options+=(--kapacitor-url="http://localhost:9092")

# Find the matching Chronograph log level
case "$(hass.string.lower "$(hass.config.get 'log_level')")" in
    all|trace|debug)
        options+=(--log-level=debug)
        ;;
    info|notice)
        options+=(--log-level=info)
        ;;
    warning|error|fatal|off)
        options+=(--log-level=error)
        ;;
esac

# Run Chronograf
exec chronograf "${options[@]}"
