#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: InfluxDB
# Runs the Kapacitor Server
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

declare secret

# Wait for InfluxDB to become available
s6-svwait -u -t 5000 /var/run/s6/services/influxdb

secret=$(</data/secret)

# Wait for InfluxDB...
hass.log.info "Kapacitor is waiting until InfluxDB is available..."
for i in {1800..0}; do
    if influx \
        -execute "SHOW DATABASES" \
        -username "kapacitor" \
        -password "${secret}" \
        > /dev/null 2>&1; then
        break;
    fi
    sleep 5
done

if [[ "$i" = 0 ]]; then
    hass.log.warning "Kapacitor is done waiting. Starting anyway..."
fi

hass.log.info 'Starting the Kapacitor'

# Run Kapacitor
exec kapacitord
